enabled: false
debug: false

welcome-message:
    enabled: false
    prefix: "<gradient:blue:white>[TELCEL]"
    message: <green>Bienvenido

force_spawn: false

firstSpawn:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    direction: SOUTH
